[User Interface]
webui_web_engine = firefox
hidden_webui_pages =
    anaconda-screen-storage-configuration
    anaconda-screen-storage-configuration-manual
    anaconda-screen-accounts
    anaconda-screen-software-selection

[Storage]
disk_label_type = gpt
file_system_type = ext4
default_scheme = PLAIN
# Blivet adds platform boot partitions; root grows without a maximum size.
default_partitioning =
    / (min 8 GiB)

[Storage Constraints]
swap_is_recommended = False
